
ZSIM_PATH="/u/yc9uf/Workspace/MultiPIM"
ZSIM_BIN_PATH="$ZSIM_PATH/build/opt"
LIB_ZSIM_PATH="$ZSIM_PATH/build/opt"
OMP_NUM_THREADS=512
OMP_SCHEDULE="static"
export PIN_PATH="$ZSIM_PATH/pin"
export ZSIM_PATH
export LIB_ZSIM_PATH
export OMP_NUM_THREADS
export OMP_SCHEDULE